---
kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: martinleydier/zwip
    tags: latest
  when:
    branch:
      - master
---
kind: signature
hmac: 97d1edc97be43a97b148a564e937ce4d0ee664346f773ffe6efe05d7f5b5a383

...
